[package]
name = "tmgr"
version = "0.1.0"
edition = "2021"
description = "Tmux utility for session and window management"
license = "Apache-2.0"

[profile.release] # min rust size resource https://github.com/johnthagen/min-sized-rus
codegen-units = 1 # There are some optimizations that prevented with multi units
lto = true        # Optimize the result in the linking phase
strip = "none"
opt-level = 3

[dependencies]
clap = { version = "4.1.11", features = [ "cargo", "derive" ] }
dirs-next = "2.0.0"
eyre = "0.6.8"
jwalk = "0.8.1"
lazy_static = "1.4.0"
rayon = "1.7.0"
serde = { version = "1.0.158", features = [ "derive" ] }
tmux_interface = "0.2.1"
toml = "0.7.3"

[[bin]]
name = "tm"
path = "src/main.rs"

[build-dependencies]
clap = { version = "4.1.11", features = [ "cargo", "derive" ] }
clap_complete = "4.1.5"
clap_mangen = "0.2.10"
