[workspace]
members = [ "crates/*" ]

[profile.release] # min rust size resource https://github.com/johnthagen/min-sized-rus
codegen-units = 1 # There are some optimizations that prevented with multi units
lto = true        # Optimize the result in the linking phase
strip = "none"
opt-level = 3
