[package]
name = "tuxmux"
version = "0.1.0"
edition = "2021"
description = "Tmux utility for session and window management"
license = "Apache-2.0"

[profile.release] # min rust size resource https://github.com/johnthagen/min-sized-rus
codegen-units = 1 # There are some optimizations that prevented with multi units
lto = true        # Optimize the result in the linking phase
strip = "none"
opt-level = 3

[dependencies]
clap = { version = "4.2.4", features = [ "cargo", "derive" ] }
dirs-next = "2.0.0"
indexmap = "1.9.3"
itertools = "0.10.5"
jwalk = "0.8.1"
kdl = "4.6.0"
miette = { version = "5.8.0", features = ["fancy"] }
rayon = "1.7.0"
shellexpand = "3.1.0"
thiserror = "1.0.40"
tmux_interface = "0.2.1"

[[bin]]
name = "tm"
path = "src/main.rs"

[build-dependencies]
clap = { version = "4.2.1", features = [ "cargo", "derive" ] }
clap_complete = "4.2.0"
clap_mangen = "0.2.10"
