[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
unsound = "deny"
notice = "deny"

[licenses]
unlicensed = "warn"
allow-osi-fsf-free = "either"
default = "deny"
allow = [ "MPL-2.0" ]

[bans]
multiple-versions = "allow"
wildcards = "deny"
highlight = "all"
