default_bin := "tm"

doc: markdown

readme:
  #!/usr/bin/env bash
  rm -f readme.adoc
  asciidoctor-reducer --output readme.adoc ./doc/readme.adoc
  echo "// Autogenerated. Edit doc/readme.adoc instead.
  $(cat readme.adoc)" >readme.adoc
  chmod 0444 readme.adoc

man:
  #!/usr/bin/env bash
  rm -f ./doc/tm.1
  version=$(cargo metadata --format-version 1 | jq -r '.packages[]|select(.name == "tuxmux")|.version')
  asciidoctor-reducer --output man.adoc ./doc/man.adoc
  asciidoctor --attribute version="$version" --doctype manpage --backend manpage --out-file ./doc/tm.1 man.adoc
  chmod 0444 ./doc/tm.1
  rm man.adoc

markdown: readme
  #!/usr/bin/env bash
  rm -f readme.md
  asciidoctor -b docbook --out-file readme.xml readme.adoc
  pandoc --wrap=none -f docbook -t gfm -o readme.md readme.xml
  # The title is lost when converting from asciidoc to docbook
  echo "#Tuxmux

  $(cat readme.md)" >readme.md
  rm readme.xml
  chmod 0444 readme.md

release:
  #/usr/bin/env bash
  cargo build --release --bin tm
  mkdir -p release/{completions,man}
  cp -f ./{LICENSE,readme.md} ./release
  cp -f ./target/release/tm ./release
  ./release/tm completions bash > ./release/completions/tm.bash
  ./release/tm completions zsh > ./release/completions/_tm
  ./release/tm completions fish > ./release/completions/tm.fish
  ./release/tm completions powershell > ./release/completions/_tm.ps1
  ./release/tm completions elvish > ./release/completions/tm.elv
  pandoc --standalone --to man doc/tm.md -o release/man/tm.1
