[package]
name = "tmgr-cmpl"
version = "0.1.0"
edition = "2021"
description = "Tmgr completion genreator"
license = "Apache-2.0"

[dependencies]
clap = { version = "4.0.4", features = [ "cargo" ] }
clap_complete = "4.0.1"
tmgr = { path = "../tmgr" }
