[package]
name = "tmgr-cmpl"
version = "0.1.0"
edition = "2021"
description = "Tmgr completion genreator"
license = "Apache-2.0"

[dependencies]
clap = { version = "3.2.20", features = [ "cargo" ] }
clap_complete = "3.2.4"
tmgr = { path = "../tmgr" }
