name: check
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
env:
  CARGO_REGISTRY_CRATES_IO_PROTOCOL: true
concurrency: # Spend CI time only on latest ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  fmt:
    runs-on: ubuntu-latest
    name: stable / fmt
    steps:
      - uses: actions/checkout@v4

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: cargo fmt --check
        run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / clippy
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta]
    steps:
      - uses: actions/checkout@v4

      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - name: cargo clippy
        uses: LoliGothick/clippy-check@v0.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deny: warnings

  doc:
    runs-on: ubuntu-latest
    name: nightly / doc
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Rust nightly
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly

      - name: Run | Cargo doc
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: --cfg docsrs

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build | Build [Cargo]
        run: cargo build --locked --target ${{ matrix.target }}
