name: documentation
permissions:
  contents: write
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - doc/**
jobs:
  docs:
    runs-on: ubuntu-latest
    name: Genreate doc files
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup | Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Build | Doc generate
        run: nix develop --command just readme

      - name: Post | Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): auto-generate readme"
