name: rolling
permissions:
  contents: read
on:
  workflow_dispatch:
  pull_request:
  schedule: # Every two weeks 1st, and 15th
    - cron: "0 0 1,15 * *"

jobs:
  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
